services:
  _defaults:
    public: true
  
  # grid
  yatpush.grid.definition.factory.women:
    public: true
    class: 'Yateo\Yatpush\Grid\Definition\Factory\WomenGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  yatpush.grid.query_builder.women:
    class: 'Yateo\Yatpush\Grid\Query\WomenQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'

  yatpush.grid.data.factory.women:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@yatpush.grid.query_builder.women'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'pushmen'

  yatpush.grid.grid_factory.women:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@yatpush.grid.definition.factory.women'
      - '@yatpush.grid.data.factory.women_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  yatpush.grid.data.factory.women_decorator:
    class: 'Yateo\Yatpush\Grid\Data\Factory\MenGridDataFactory'
    arguments:
      - '@yatpush.grid.data.factory.women'
      - '@yatpush.adapter.women.women_logo_thumbnail_provider'
  
  yatpush.adapter.women.women_logo_thumbnail_provider:
    class: 'Yateo\Yatpush\Adapter\LogoThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'

  # Position

  yatpush.women.grid.position_definition:
    class: 'PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition'
    arguments:
      $table: 'yateo_push'
      $idField: 'id_yateo_push'
      $positionField: 'position'
