yatpush_pushmen: 
  path: / 
  methods: GET 
  defaults: 
    _controller: 'Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::indexAction' 
    _disable_module_prefix: true
    _legacy_controller: 'YatpushConfigurationMenController' 
    _legacy_link: 'AdminYatPushMenCategory' 

yatpush_pushmen_search: 
  path: / 
  methods: POST 
  defaults: 
    _controller: 'Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::searchAction' 
    _disable_module_prefix: true
    _legacy_controller: 'YatpushConfigurationMenController' 
    _legacy_link: 'AdminYatPushMenCategory' 

yatpush_pushmen_create:
  path: /create
  methods: [GET, POST]
  defaults:
    _controller: Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::createAction
    _disable_module_prefix: true
    _legacy_controller: 'YatpushConfigurationMenController'
    _legacy_link: 'AdminYatPushMenCategory'

yatpush_pushmen_edit:
  path: /{pushId}/edit
  methods: [GET, POST]
  defaults:
    _controller: Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::editAction
    _disable_module_prefix: true
    _legacy_controller: 'YatpushConfigurationMenController'
    _legacy_link: 'AdminYatPushMenCategory'
  requirements:
    pushId: \d+

yatpush_pushmen_delete:
  path: /{pushId}/delete
  methods: [GET, POST]
  defaults:
    _controller: Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::deleteAction
    _disable_module_prefix: true
    _legacy_controller: 'YatpushConfigurationMenController'
    _legacy_link: 'AdminYatPushMenCategory'
  requirements:
    pushId: \d+

yatpush_delete_image:
  path: /yatpush/{pushId}/delete/image
  methods: [POST]
  defaults:
    _controller: Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::deleteImageAction
    _disable_module_prefix: true
    _legacy_controller: 'YatpushConfigurationMenController'
    _legacy_link: 'AdminYatPushMenCategory'
  requirements:
    pushId: \d+

yatpush_pushmen_toggle_status:
  path: /{pushId}/togglestatus
  methods: [GET, POST]
  defaults:
    _controller: Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::toggleAction
    _disable_module_prefix: true
    _legacy_controller: 'YatpushConfigurationMenController'
    _legacy_link: 'AdminYatPushMenCategory'
  requirements:
    pushId: \d+

yatpush_pushmen_update_positions:
  path: /update-positions
  methods: [POST]
  defaults:
    _controller: 'Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::updatePositionsAction'
    _legacy_controller: YatpushConfigurationMenController
    _legacy_link: 'AdminYatPushMenCategory'

yatpush_pushmen_bulk_status_disable:
  path: /bulk-disable-status
  methods: [POST]
  defaults:
    _controller: 'Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::bulkStatusDisableAction'
    _legacy_controller: YatpushConfigurationMenController
    _legacy_link: AdminYatPushMenCategory

yatpush_pushmen_bulk_status_enable:
  path: /bulk-enable-status
  methods: [POST]
  defaults:
    _controller: 'Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::bulkStatusEnableAction'
    _legacy_controller: 'YatpushConfigurationMenController'
    _legacy_link: 'AdminYatPushMenCategory'

yatpush_pushmen_delete_bulk:
  path: /delete-bulk
  methods: POST
  defaults:
    _controller: 'Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::deleteBulkAction'
    _legacy_controller: YatpushConfigurationMenController
    _legacy_link: AdminYatPushMenCategory

yatpush_pushmen_export:
  path: /export
  methods: [GET]
  defaults:
    _controller: Yateo\Yatpush\Controller\Admin\YatpushConfigurationMenController::exportAction
    _legacy_controller: YatpushConfigurationMenController
    _legacy_link: AdminYatPushMenCategory

