services:
  _defaults:
    public: true

  # GRID
  yhc.grid.grid_factory.men:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@yhc.grid.definition.factory.men'
      - '@yhc.grid.data.factory.men_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
  
  yhc.grid.definition.factory.men:
    public: true
    class: 'Yateo\Yathomecategories\Grid\Definition\Factory\MenGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
  
  yhc.grid.data.factory.men_decorator:
    class: 'Yateo\Yathomecategories\Grid\Data\Factory\MenGridDataFactory'
    arguments:
      - '@yhc.grid.data.factory.men'
      - '@yhc.adapter.men.men_logo_thumbnail_provider'
  
  yhc.grid.data.factory.men:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@yhc.grid.query_builder.men'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'MenCategories'

  yhc.adapter.men.men_logo_thumbnail_provider:
    class: 'Yateo\Yathomecategories\Adapter\LogoThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'

  yhc.grid.query_builder.men:
    class: 'Yateo\Yathomecategories\Grid\Query\MenQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'