services:
  _defaults:
    public: true

  # GRID
  yhc.grid.grid_factory.women:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@yhc.grid.definition.factory.women'
      - '@yhc.grid.data.factory.women_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
  
  yhc.grid.definition.factory.women:
    public: true
    class: 'Yateo\Yathomecategories\Grid\Definition\Factory\WomenGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
  
  yhc.grid.data.factory.women_decorator:
    class: 'Yateo\Yathomecategories\Grid\Data\Factory\WomenGridDataFactory'
    arguments:
      - '@yhc.grid.data.factory.women'
      - '@yhc.adapter.women.women_logo_thumbnail_provider'
  
  yhc.grid.data.factory.women:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@yhc.grid.query_builder.women'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'MenCategories'

  yhc.adapter.women.women_logo_thumbnail_provider:
    class: 'Yateo\Yathomecategories\Adapter\LogoThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'

  yhc.grid.query_builder.women:
    class: 'Yateo\Yathomecategories\Grid\Query\WomenQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'

  yhc.form.category_women_configuration:
    class: Yateo\Yathomecategories\Form\Data\CategoryConfigWomenFormData
    arguments: ['@prestashop.adapter.legacy.configuration']

  yhc.form.category_women_configuration_data_provider:
    class: 'Yateo\Yathomecategories\Form\Provider\CategoryConfigFormDataProvider'
    arguments:
      - '@yhc.form.category_women_configuration'
  
  yhc.form.category_women_configuration_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@yhc.form.category_women_configuration_data_provider'
      - 'Yateo\Yathomecategories\Form\Type\YHCWomenConfigType'
      - 'CategoryWomenConfiguration'